### ISSUE TITLE
BInfoWindow的信息窗口 投射的阴影想问下怎么去除

### ISSUE THREAD

**Issue by kood-2008** [yue1123/vue3-baidu-map-gl#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yue1123** [comment]
用 css 去除：
```css
.baidu-map-container .shadow{
    opcity: 0;
}
```
